version: '3'
services:
  web:
    image: fpfis/httpd-php-dev:7.3
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html # Non Mac users.
      # - ~/.cache/composer:/root/.composer/cache # use a local cache.
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # ports:
      # - 3306:3306
  # Spawn a Selenium server which also includes a VNC server on localhost:5900 (the password is "secret")
  selenium:
    image: selenium/standalone-chrome-debug:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    ports:
      - 5900:5900
    expose:
      - 4444
  authentication:
    # For local access, run this command in the terminal
    # echo "127.0.1.1       authentication" >> /etc/hosts
    image: registry.fpfis.eu/fpfis/eulogin-mock-server:6.2.7
    volumes:
      - ./tests/fixtures/mock-server-config:/data/ecas-mock-server-shared
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003

#### Secure container: provide a https proxy to access to website with https.
#### @see: README.md#development
#
#  secureweb:
#    image: aheimsbakk/https-proxy:4
#    ports:
#    - 80:80
#    - 443:443
#    links:
#    - web:http
#    restart: always
#    volumes:
#    - ./tests/fixtures/certs/secureweb:/etc/ssl/private
#    environment:
#    - SERVER_NAME=secureweb
#    - SERVER_ADMIN=webmaster@mydomain.com
#    - PORT_REDIRECT=8080
#    - SSL_CERT_FILE=/etc/ssl/private/MyKeystore.crt
#    - SSL_PRIVKEY_FILE=/etc/ssl/private/MyKeystore.key
#    - SSL_CHAIN_FILE=/etc/ssl/private/MyKeystore.p12
#
#### End Secure container.

#### Mac users: uncomment the "volumes" key to enable the NFS file sharing.
#### You can find more information about Docker for Mac here:
#### https://github.com/openeuropa/openeuropa/blob/master/docs/starting/tooling.md#using-docker-on-macos
#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#      device: ":${PWD}/"
#### End Mac users.
